---
abstract: "wrapper to rsync/etc. to upload files to a remote server and give\ndownload links."
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  File::Spec: 0
  Module::Build: 0.3601
  Test::Differences: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Sky
requires:
  Carp: 0
  Exception::Class: 0
  File::Basename: 0
  File::HomeDir: 0
  Getopt::Long: 0
  List::MoreUtils: 0
  List::Util: 0
  Moo: 0
  MooX: 0
  MooX::late: 0.010
  Scalar::Util: 0
  URI: 0
  YAML::XS: 0
  strict: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=App-Sky
  homepage: http://www.shlomifish.org/open-source/projects/sky/
  repository: git://github.com/shlomif/Sky-uploader.git
version: 0.0.4
